image: docker:latest

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

services:
  - docker:dind

stages:
  - build

build_image:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t "$IMAGE_NAME" -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$IMAGE_NAME"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - main
